### ISSUE TITLE
Trying to run under Linux

### ISSUE THREAD

**Issue by ZirconiumX** [bsutherland/JuceOPLVSTi#21]
I gave up attempting to build a native version of this VST (Steinberg's SDKs are somewhat awkward to get hold of, and JUCE makes you jump through hoops before giving you something that does not work (it will not save as a makefile))

So I tried to run the 32-bit DLL under VeSTige, and was almost successful. It crashes trying to display the GUI though. Is there any way you could either remove the GUI or provide an alternate interface?

Matthew:out

**Comment by ZirconiumX** [comment]
Don't worry, it's only been a year and a half. In that time, I bit the bullet and got Windows 10, and JOV works fine under Cubase when in ZDoom emulation (I get the 120dB DC issue on the DosBox emu).

I'm going to close this, because I don't have a system to test on, nor do I have the foggiest idea where to begin in the code.

**Comment by bsutherland** [comment]
For anyone still interested in building under Linux, I made some small changes to the code and added some instruction to the README courtesy of Dave Phillips.

His original instructions here:

https://www.linuxmusicians.com/viewtopic.php?f=19&t=15485
