### ISSUE TITLE
Inverted ADSR parameters and some tests

### ISSUE THREAD

**Issue by ghost** [bsutherland/JuceOPLVSTi#22]
I just open a new issue to keep it organized, but really, I'm more grateful than other thing.
I've been playing it a lot (version 0.9.7 32bits).

I'm using Windows 7 64-bits. 
Here's some tests I've made:

### Ableton Live 8 32-bits
Working fine with ASIO drivers. When using default MME/DirectX drivers it seems as if an LFO were applied to it in which I would change "its modulation frequency" by changing the buffer size.
Drag-and-drop .SBI files not working! The cursor shows as if it weren't possible. Did it work in Ableton Live 9 64-bits on your lastest build?

### vsthost.exe
I've downloaded this simple VST host from [here](http://www.hermannseib.com/english/vsthost.htm)
It does work with MME/DirectX drivers. Drag-and-drop also works! 

While mapping everything into my MIDI keyboard I only found that ADSR parameters are inverted, in both tests. Did it happen to you?

I've used the (Ableton) Device inherit parameters to do the midi mapping. When I move a mapped knob changes are not reflected into the UI, only in the Ableton Device ones. But that's no problem!

After all, it's like having the Soundblaster inside my actual machine! I've been looking for this for years. I even bought a Yamaha XG which contains the OPL3 chip, but I never could made it work.

###### Update:
I've tested 0.10.1 64-bit build in vsthost.exe to try it out. I would decrease some dbs instead! just because it easily clips when doing polyphony. I think it would be better to increase the output from our mixers, but just that.
I'll take a look at the ZDoom emulation :)

Thanks for all man...

**Comment by bsutherland** [comment]
Levels dropped in 0.11.1
