### ISSUE TITLE
Plugin doesn't set VST unique ID

### ISSUE THREAD

**Issue by sagamusix** [bsutherland/JuceOPLVSTi#24]
JuceOPLVSTi uses the default plugin ID provided by Juce, which may confuse some hosts when using more than one Juce plugin which doesn't set this value. In the Introjucer config, find the "Plugin Code", whose value is currently "Plug", and change it to something more unique, e.g. "JOPL" or something like that (it needs to be four letters). Similarly, the "Plugin Manufacturer Code" should probably be changed to something like "Suth" or something like that, but that's not required for VST at least (but maybe for another plugin type?)

**Comment by bsutherland** [comment]
Added required properties. Will be fixed in next release.
