### ISSUE TITLE
Plugin not detected by Ableton 9.1 x64

### ISSUE THREAD

**Issue by bladeSk** [bsutherland/JuceOPLVSTi#27]
It seems the issue is, that Ableton treats plugins whose filename doesn't end with `x64` like 32-bit plugins, so 64-bit dlls are seen as broken and don't get loaded.
The solution is to simply rename the file to something like `JuceOPLVSTi x64.dll`. After that it works fine.

**Comment by bsutherland** [comment]
Nice find. I'll keep that in mind for future builds.
