### ISSUE TITLE
Some values not saving correctly in FL Studio

### ISSUE THREAD

**Issue by PoniestPonypony** [bsutherland/JuceOPLVSTi#30]
I am using 0.11.1 (x64) of the JuceOPLVSTi in FL Studio 11.1.1. (x64).  Certain attack, decay, sustain, and release values do not save correctly; i.e. upon loading a project, some of the values will have decreased by 1.

For example, the ADSR of either the carrier or modulator can be set to 14, 4, 8, 11, respectively.  After saving the project as an FLP, then reloading the project, the ADSR values will change to 13, 4, 7, 10, respectively (the value "4" does not change for some reason, but the others do).

**Comment by bsutherland** [comment]
Thanks for the report! Not sure when I'm going to get a chance to look at this next though I'm afraid :(

**Comment by litaniast** [comment]
0.12 version also has this bug.

**Comment by litaniast** [comment]
It seems fixed in 0.13.1. no longer appeared.

**Comment by bsutherland** [comment]
Great, thanks for verifying!
