### ISSUE TITLE
Nothing but sound glitches

### ISSUE THREAD

**Issue by StigNasty** [bsutherland/JuceOPLVSTi#31]
OS X AU version (Logic X 10.2.0 OS X Yosemite).

Hey, this is one of the most fantastic ideas I've come across in some time, and the gui looks really nice. Sadly, after authorizing in Logic, I opened it up and all it does is give me random glitches, with no change in sound when I press keys or input midi information. If I switch emulators away from the Dosbox emu the glitches stop, but no sound comes from the plugin. Is this something that is known or am I alone in it?

Thanks!

**Comment by bsutherland** [comment]
Stig, sorry for the slow reply.

Did you build it yourself from the latest source? Or did you download Jeff Russ' binaries from here:
http://jeff-russ.github.io/AdlibBlaster/

I merged Jeff's changes into this repo, but I'm afraid I don't have Mac, so I can't build or test under OSX :(

**Comment by Zuldra** [comment]
StigNasty, are you running at 44.1?

**Comment by Jeff-Russ** [comment]
@StigNasty   @StigNasty 
This is by no stretch a "release" but I had some free time to I fired up Xcode. I just made a few changes and it compiled. It ran with no __major__ issues in OSX 10.10 Logic Pro X and OSX 10.10 Ableton Live 9 as both AUi and VSTi. I _didn't test it very much_ but see if this fixes things... 

[Download AUi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-vst_Jeff-Russ_build160207.zip)
[Download VSTi](https://s3.amazonaws.com/adlibblaster/osx/JuceOPL-au_Jeff-Russ_build160207.zip)
[my fork of JuceOPLVSTi](https://github.com/Jeff-Russ/AdlibBlaster)

**Comment by bsutherland** [comment]
The latest Windows release has a fix which *might* fix this issue.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

**Comment by bsutherland** [comment]
Thanks for the build Jeff! I'm closing this for now since the original reporter never wrote back.
