### ISSUE TITLE
Consider support for sample rates other than 44.1 kHz

### ISSUE THREAD

**Issue by Zuldra** [bsutherland/JuceOPLVSTi#33]
Hi,

This plugin is entirely unusable at 96 khz.

It only outputs a corrupted buffer sound with a gigantic DC offset that will be auto-muted if you're lucky.

I don't use 44.1 for production therefore I cannot use this plugin.

**Comment by bsutherland** [comment]
Yep, it's locked at 44.1 kHz. That's written clearly in the readme, and there are no plans to change it. It would be pretty meaningless anyway as the internal sample rate of the OPL chip was 49716 Hz.

**Comment by bsutherland** [comment]
But thanks for pointing this out.. this might explain issues that other people had! It would be nice if there was a way for a VST plugin to tell a host that the sample rate is locked. :(

**Comment by Zuldra** [comment]
That makes me sad :(

**Comment by ZirconiumX** [comment]
The ZDoom emulator works fine at 48kHz, though. Surely it wouldn't be too hard to allow 48kHz on the DOSBox emulator too?

**Comment by bsutherland** [comment]
Really?? That's surprising. And interesting :)

**Comment by bsutherland** [comment]
So I just tested it in Renoise. In Renoise, I get audio in both ZDoom and DOSBox mode, but as expected it's detuned. I'll see what I can do about it.

This is the only VST plugin I've written, and I've learned that not all VST host software is equal. Renoise seems to do a great job of handling it, but some other apps not so much.

**Comment by ZirconiumX** [comment]
Under Cubase, anything other than 48kHz results in detuned sound, though I
think that's because my sound card is set to 48kHz, rather than 44.1kHz.

Maybe try setting your sound card to 48 and seeing what happens there.

**Comment by ZirconiumX** [comment]
Slightly unrelated, but what happens when you modify OPL_SAMPLE_RATE in
zdopl.h to be 44100 and remove the 2 semitone hack in Hiopl::SetFrequency?

I think you're trying to deliver a 49716Hz waveform as 44100Hz and getting
pitch shifting as a result.

**Comment by bsutherland** [comment]
OK, by popular request:

http://bsutherland.github.io/JuceOPLVSTi/

ZirconiumX: Thanks, I tried that, but the OPL_SAMPLE_RATE setting doesn't seem to change output frequency. For this build I've dropped ZDoom support, but got sample rate changes working with DOSBox. Any fixes / features are greatly appreciated, feel free to fork.

**Comment by Zuldra** [comment]
Hello Bruce

Thank you so much for working on this. I appreciate it so much. You really
are a wizard.

Hearing the OPL synth brings a tear to my eyes.

There seems to be a bug with the 96 Khz support because it sounds like a
ring modulation / a stream of crackles.

**Comment by ZirconiumX** [comment]
That's not the 96kHz, that's output clamping. I filed a ticket for that.

**Comment by bsutherland** [comment]
Zuldra, which VST host are you using? It seems to fail at 96 kHz on Cubase, but works in renoise. I'm going to try to track it down, but it might take some time.

**Comment by Zuldra** [comment]
Hi Bruce

I use REAPER 64 bit

Thanks so much for checking
