### ISSUE TITLE
Distortion under Cubase

### ISSUE THREAD

**Issue by ZirconiumX** [bsutherland/JuceOPLVSTi#35]
So, I've just downloaded 0.12.1, and while the DOSBox emu doesn't produce huge amounts of noise anymore, it does seem to have a distortion to it, which 0.11.1's ZDoom didn't have.

For the sake of reproducibility, I have attached a zip file containing:
* An OGG mixdown of the Tubular Bells riff using the Death Toll Bell preset
* A MIDI of said Tubular Bells riff

I'm using Cubase Elements 8.

[OPL.zip](https://github.com/bsutherland/JuceOPLVSTi/files/120678/OPL.zip)

**Comment by ZirconiumX** [comment]
I suspect this is due to the output clamping you're doing. 

Googling suggests trying to use hyperbolic tangent to soft clip, rather than hard clip.

**Comment by bsutherland** [comment]
It's really strange.. I wonder why it clips on some VST hosts and not others?

Thanks for the recordings. I won't be able to work on the VST for a while, but when I do I'll see if I can download a Cubase demo and experiment.

If you're up for it, feel free to jump in and hack on it ;-)

**Comment by ZirconiumX** [comment]
I've been trying to do exactly that, but Cubase is having issues
recognising the VST. I'm using VS2015, but that shouldn't make any
difference. Perhaps it's compiling as 32-bit?

**Comment by bsutherland** [comment]
Hm.. did you add a new export target in the Projucer for Visual Studio 2015? Or are you opening the 2013 project file and upgrading it that way?

**Comment by ZirconiumX** [comment]
I am using a dedicated 2015 export target, since upgrading doesn't work for
some reason.

**Comment by bsutherland** [comment]
Did you set architecture to x64 in Projucer? Which VST SDK version are you using?

**Comment by ZirconiumX** [comment]
I'm not at home right now, so I can't check for definite, but I think so,
and I think I was using 3.6.1.

**Comment by bsutherland** [comment]
I see. I always built it under 2013 using an older SDK (2.4 I think). I'll try upgrading everything and see how it goes.

**Comment by ZirconiumX** [comment]
I'm sure I've read in the docs that juce has an option to use the VST3 SDK
as VST2, but I can't remember what it is.

Also, since you know how to use Juce, could I suggest a percentage option
to control/reduce audio output in the GUI? I'm sure that would reduce the
clipping people like me are getting.

**Comment by bsutherland** [comment]
OK, I've got it building under 2015 with the VST 3 SDK.

The gain control suggestion is a great idea.. don't know why I didn't think of that before!

**Comment by ZirconiumX** [comment]
Logically, just multiply it by the percentage as decimal, and then clamp
the result after that. That should give headroom without excessive
clamping. I'd suggest possibly 50% as default?

**Comment by bsutherland** [comment]
OK, I haven't implemented gain control, but I just tested the latest build in Cubase LE AI Elements x64 version 8 (trial) and there was no clipping with the Death Toll Bell preset and the midi file you uploaded.

Please try this and let me know.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.12.2

**Comment by ZirconiumX** [comment]
Still clipping badly.

**Comment by bsutherland** [comment]
Hm.. given that it works on Cubase on my machine, possible variables that I can think of:

- Configuration (especially latency / buffering.. turning it up solved the issue for somebody else)
- Cubase version (I'm on LE AI Elements v8 64-bit, trial version)
- Drivers
- Host operating system (I'm on Windows 7)
- Hardware??

I'm guessing one of these is interacting badly with something in the plugin code.

**Comment by ZirconiumX** [comment]
>Configuration
I've been using a 20ms buffer that's been working absolutely fine for everything else. (Part of me wonders if PrepareForPlayback is designed to allow for variable buffer sizes)
>Cubase Version
Cubase LE AI Elements 8.0.35 (64-bit)
>Drivers
My SMSL M2 is using the default Windows Sound over USB driver, and my Creative drivers are up to date and work fine for everything else.
>Hardware
The problem occurs with both my SMSL and my Creative card.

So, TODO list for this in my opinion would be:
* implement gain control
* fix PrepareForPlayback to use the buffer settings that the host gives

**Comment by bsutherland** [comment]
OK, so I've finally managed to reproduce it. In Cubase at 96 kHz, the plugin misbehaves. It works fine at 44.1 and 48 kHz. It also works at 96 kHz in Renoise. I'll look into it more when I have time.. thinking to add a debug console to try and understand what Cubase and Renoise are doing differently.

About the buffers.. the buffer size passed by the host to `prepareToPlay` is just a hint:
https://www.juce.com/doc/classAudioSource#a653279dbd167f70e318fd280681dbddf

The actual buffer size can vary per block and is passed to the `processBlock` method as part of the `AudioSampleBuffer` object. The plugin respects that value.

**Comment by ZirconiumX** [comment]
I can't help but wonder - why did ZDoom work, but DOSBox doesn't? There
must have been something in the deleted code that meant that the ZDoom code
worked. But what?

Maybe we need to ask a ZDoom dev, since I don't understand the code fully,
and perhaps you don't, either.

**Comment by Jeff-Russ** [comment]
I never got zdoom to work in the Mac build. JuceOPLVSTi uses some data types defined in the Window framework which I tried to copy into the plugin from the MS documentation but I would not surprise me if a few are off.

**Comment by bsutherland** [comment]
I can't test under Cubase (no license), but the latest release has a fix which *might* solve this issue. Please let me know:

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

**Comment by ZirconiumX** [comment]
Yes, this appears to have fixed the issue. Thank you.

**Comment by bsutherland** [comment]
Thanks a lot for verifying!

:tada:
