### ISSUE TITLE
Add support for .ins instruments

### ISSUE THREAD

**Issue by litaniast** [bsutherland/JuceOPLVSTi#36]
[bbr-gmus.zip](https://github.com/bsutherland/JuceOPLVSTi/files/186381/bbr-gmus.zip)

This is sbi files that used in Korean adlib music users. Originally for .bnk file and extracted to .sbi. Of course some of them are duplicated in AdlibTracker and synth-bbs but there are lots of awesome instruments.

Enjoy!

**Comment by bsutherland** [comment]
Great, thank you very much! I'll sort out the duplicates and add them to the repository soon.

**Comment by litaniast** [comment]
I think it's good there is also support .ins/.bnk format instruments support. Because, in the 90's OPL2 music in Korea, they used Visual Composer and it used .bnk format created in Insmaker. Of course we can extract .sbi from .bnk, but if .bnk file is too big, we can't do it because of 'out of memory' message.

**Comment by bsutherland** [comment]
I had a quick look, and it shouldn't be too hard to support .ins format. Do you have some .ins files as an example?

Handling .bnk will be a bit more complicated, because there can be multiple instruments in one file, so there would need to be a UI to handle that.

**Comment by litaniast** [comment]
http://sierrahelp.com/SCI/Tools/SCISoundTools.html

You can easily extract .SBI/.INS file from .BNK.
But I thought again, .INS support is not so useful because when they used Visual Composer, they used .BNK files instead of seperated .INS. (and if we need extract in .BNK, it's not so different using .SBI and .INS)

**Comment by bsutherland** [comment]
Thank you very much for contributing the SBI files! I've finally added them in the latest release, and deleted all the duplicates.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

I'll leave this issue open for INS support.

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, and does everything which JuceOPLVSTi does and more. In case you're interested:

https://github.com/jpcima/ADLplug

Sorry to say, but I'm closing all enhancement requests on this project, as I don't plan on enhancing it from here on.
