### ISSUE TITLE
Sound is only left channel in 0.12.1

### ISSUE THREAD

**Issue by litaniast** [bsutherland/JuceOPLVSTi#37]
When I used JuceOPLVSTi in 0.11.1. Although that's mono output(because original OPL2 has mono sound), it has both left and right channels correctly.

But when I upgraded 0.12.1, the sound is only hearing in left channel only, I need to balance edit manually. it's normal behavior? or bug of this version?

I'm using FL Studio 12(x64) in Windows 10.

**Comment by bsutherland** [comment]
Sounds like a bug. Thanks for letting me know!

**Comment by Vospi** [comment]
Same here, FL Studio 11.1.1

**Comment by bsutherland** [comment]
Thanks for the report vospi. Having a bit of a crazy week at work but
hoping to get some time for this on the weekend.

**Comment by Vospi** [comment]
Not at all, thank you for the amazing instrument.

**Comment by Deraidos** [comment]
I have this problem as well (FL Studio 11 on Windows 7)

**Comment by bsutherland** [comment]
Thanks for the report Deraidos. This is definitely #3 on the list to fix in the next release.

**Comment by bsutherland** [comment]
I've tested the latest release using FL Studio 12 (64 bit) on Windows 7, and I'm getting sound from both channels now. May have been fixed by updating the Juce modules.

Please let me know if you still have trouble.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

**Comment by Vospi** [comment]
FL v11.1.1 x86, and it works perfectly well. Thank you very much for
curating this project for and making it real, the authentic sound is
stellar and very useful.

2016-05-14 15:37 GMT+03:00 Bruce Sutherland <notifications@github.com>:
