### ISSUE TITLE
Needs a library/preset interface

### ISSUE THREAD

**Issue by kraed** [bsutherland/JuceOPLVSTi#38]
This plugin should have a library menu in which to read, scroll through, add and choose presets with. The drag and drop functionality is not bad but is super unpractical for composing and sound design. Amazing plugin, will continue to use, very useful for video game music.

**Comment by bsutherland** [comment]
Thanks for the suggestion. That would definitely be handy, I'll consider it for a future release.

**Comment by bsutherland** [comment]
See also https://github.com/bsutherland/JuceOPLVSTi/issues/50

**Comment by bsutherland** [comment]
@gdreyband Could we please move the discussion on the preset UI here? The other ticket might get a bit large otherwise :)

**Comment by gdreyband** [comment]
Sure, sorry :)

I tend to turn these things into conversations rather than bugs/feature requests.

**Comment by bsutherland** [comment]
I'm looking for advice from people with experience with a lot of VST plugins (I don't have it..)

I've been Googling around to see what the "standard" solution is for presets. It seems like .fxb files might be a good option that is supported by most DAWs. Does that seem correct though?

I don't want to reinvent the wheel - it seems surprising to me that every VST would need to implement it's own interface for presets.

**Comment by gdreyband** [comment]
That's beyond me, .fxb seems to be pretty universal, but I can't say for sure. I know that Green Oak Software's Crystal (a very old but still very powerful VST) uses .fxb, and it's Win and Mac.

**Comment by bsutherland** [comment]
Sorry to say, but I'm closing all enhancement requests on this project, as I don't plan on enhancing it from here on. As you probably noticed, ADLplug supports banks.
