### ISSUE TITLE
panic button

### ISSUE THREAD

**Issue by Moth-Tolias** [bsutherland/JuceOPLVSTi#39]
is it at all possible to implement a panic button? sometimes, while under heavy usage, a key will get "stuck" on the sustain, with no way to stop it other than unloading the vst.

**Comment by bsutherland** [comment]
Thanks for letting me know.

Panic button sounds like a good temporary measure. Longer term, I'd like to find the cause of the stuck notes. I'll try to reproduce it.

**Comment by bsutherland** [comment]
If it can reproduce the issue, it couldn't hurt! Please feel free to upload to this ticket.

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, and does everything which JuceOPLVSTi does and more. It includes a panic button. In case you're interested:

https://github.com/jpcima/ADLplug

Sorry to say, but I'm closing all enhancement requests on this project, as I don't plan on enhancing it from here on.
