### ISSUE TITLE
Sound distortion in Reaper

### ISSUE THREAD

**Issue by TheDevelo** [bsutherland/JuceOPLVSTi#40]
Getting sound distortion in Reaper. The severity of the distortion is based on the sample rate. Only happens in v0.12.1 and up.

I attached some examples along with a mix using v0.11.1.
[OPL-bug.zip](https://github.com/bsutherland/JuceOPLVSTi/files/226925/OPL-bug.zip)

**Comment by bsutherland** [comment]
Thanks for the report. I *think* I know the cause of this now thanks to somebody who looked at the code.. just waiting to get time to work on this!

**Comment by bsutherland** [comment]
I reproduced and fixed this in Reaper 5.18 (x64) on Windows.

Please try the latest release and let me know if you still have trouble.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.1

**Comment by TheDevelo** [comment]
Works perfectly. Thanks!
