### ISSUE TITLE
Not working under Windows 10

### ISSUE THREAD

**Issue by litaniast** [bsutherland/JuceOPLVSTi#41]
![juceoplvsti_error](https://cloud.githubusercontent.com/assets/4857928/15268790/28303208-1a25-11e6-9a37-2818cd9815c7.png)

Windows 10 x64 / FL Studio 12.2 x64

**Comment by bsutherland** [comment]
Thanks for letting me know. I think this might be a Windows 10 issue only. I've tested it with FL 12.2 32-bit and 64-bit under Windows 7.

**Comment by litaniast** [comment]
Update: It also isn't working on other DAWs (Studio One 2, Cubase AI 8) under Windows 10. In Win7, working fine on FL confirmed.

**Comment by bsutherland** [comment]
OK, that's useful to know. Thanks.

**Comment by nix808** [comment]
Hi,
TY so much for this unique VSTi. I wanted to chime in here to say that I have been trying to run the latest public build in Win10. It is also inoperable in Buzz Machines and Orion. Simply does nothing on load, ie. no UI, no window. The ver 0.12.1 however works fine in Orion. I can test Reaper,FL12.3 and Cubase(in the mail) soon- within a couple of weeks. Cheers- Nick (PhonicsAudio)

**Comment by bsutherland** [comment]
Thanks, testing is appreciated. Interesting that 0.12.1 works on Windows 10.. But orion only right?

**Comment by litaniast** [comment]
0.12.1 works fine in FL Studio 12/Cubase 8/Studio One 2 under Windows 10.

**Comment by nix808** [comment]
0.12.1 also works fine in Reaper 4.54
Buzz has some problem though.
The vst displays the voice triggers, but audio out doesn't work.
I think it's something to do with the stereo audio outs of OPL.
The Polac VSTi loader in Buzz Machines usually works really good.
I'm not sure you want to bugfix this one, not many use Buzz,
but it's free if you'd like to try in a modular host.

Also the latest 32-bit version is working perfect in every host I've tried, after realising what is happening with some stuck notes, it is not the OPL build.

**Comment by bsutherland** [comment]
Thanks to both of you for confirming.

**Comment by bsutherland** [comment]
Sorry for the long time between releases.

I've updated Visual Studio 2015 from update 1 to update 3, and my Juce version. I also built 32-bit and 64-bit this time.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.2

Please let me know if you still have issues under Windows 10.

**Comment by litaniast** [comment]
It's now works well in Windows 10(on above all DAWs)! Thanks for fix bugs.

**Comment by bsutherland** [comment]
Great! Thanks a lot for taking the time to confirm litaniast.
