### ISSUE TITLE
Velocity not triggering correctly in FL Studio 12

### ISSUE THREAD

**Issue by Alestance** [bsutherland/JuceOPLVSTi#42]
Using Velocity in JuceOPLVSTi doesn't work properly. I'm not sure how, exactly, to explain what the issue is, but it seems that velocity is being stored in the vst and occasionally triggers with the stored velocity rather than the velocity the DAW has set. This affects both modulator and carrier. I don't know if its an issue with the DAW or with the VST, because I remember using velocity to control the strength of the modulator without issues in earlier versions of both FL Studio and JuceOPLVSTi.

**Comment by bsutherland** [comment]
Thanks for the report. There is another open issue related to velocity, but I'm not sure if it is the same problem. Either way, I'll take a look for the next release.

**Comment by bsutherland** [comment]
Not fixed yet, but adding link to this existing issue:
https://github.com/bsutherland/JuceOPLVSTi/issues/26
