### ISSUE TITLE
Load .sbi file button (enhancement)

### ISSUE THREAD

**Issue by Vospi** [bsutherland/JuceOPLVSTi#43]
There's [a question on KVR forum](https://www.kvraudio.com/forum/viewtopic.php?f=1&t=448996) which goes like this:

_For some of my VSTs to be made available I've got to run Ableton in admin mode which unfortunately prevents any drag and drop functionality from Explorer due to the a lack of permissions. As there's no file-open dialog in this (otherwise awesome) VSTi, does anyone know a way of loading the additional .sbi files it comes bundled with ?_

**Comment by bsutherland** [comment]
Thanks for letting me know vospi. Somebody else requested a better UI for opening SBI Giles, so I'll try to solve this at the sane time.

**Comment by bsutherland** [comment]
Added in latest release:

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.2
