### ISSUE TITLE
x86 .dll for Windows 10?

### ISSUE THREAD

**Issue by nix808** [bsutherland/JuceOPLVSTi#44]
Hi,
I was just wondering if we could get a 32 bit build of 0.13.1?
The older one hangs MIDI occasionally, but the 0.13.1 doesn't.
Cheers and ty

**Comment by bsutherland** [comment]
I was hoping to drop support for 32-bit, since most machines are 64-bit now. Were you hoping to run it on an older machine or is there another reason? Thanks.

**Comment by nix808** [comment]
Hey 8D
The reason for the request is that I run a 32-bit vst fx that turns my hexaphonic guitar audio into MIDI. If I had a current 32-bit .dll I could run it in 1 host application. The environment where I have built it(the guitar/MIDI vst),Flowstone,does not export to x64 yet. To amend the first post, the audio hangs are not due to ver 11.1, but to host environment MIDI interpretation(speed?)- so I can run the 32 bit version. However, if you would consider 32 bit builds of current updates, that would be real nice for me-- I am sure to be using this a lot, really inspiring sound. Some of us will be composing on 32-bit hosts within a 64 bit OS.

**Comment by bsutherland** [comment]
So, if I'm understanding this right, you want to drive the VST using an electric guitar?

Hell, that's a good enough reason for me. I expect to hear Doom E1M1 performed live though :)

**Comment by nix808** [comment]
Niice! Yes, I play VSTs with guitar.
Here is the first time I have used OPL in a trackish format->
https://soundcloud.com/nix808/leed-master
OPL is the bass and lead

**Comment by bsutherland** [comment]
Sorry for the very slow reply!! I finally got round to doing a new release. 32-bit and 64-bit.

https://github.com/bsutherland/JuceOPLVSTi/releases/tag/0.13.2

Thanks a lot for the link too!
