### ISSUE TITLE
Binary AU 0.11.1 broken

### ISSUE THREAD

**Issue by Flei** [bsutherland/JuceOPLVSTi#47]
There is no binary in the .component but there is a symlink to `/Users/Jeff/Library/Audio/Plug-Ins/Components/JuceOPLVSTi.component`.

**Comment by bsutherland** [comment]
Thanks Flei, sorry for the slow response.

I'll let Jeff know next time he has time to do an OSX build.

**Comment by bsutherland** [comment]
Please try the most recent release. Thanks!

**Comment by Jeff-Russ** [comment]
I believe these are the most recent builds for MacOS

[download AUi](https://drive.google.com/open?id=0B3RK-KfkucDQMmpBX21scUEtMjg)  
[download VSTi](https://drive.google.com/open?id=0B3RK-KfkucDQZWFlT3YwSEUxaTQ)

**Comment by bsutherland** [comment]
Thanks a lot as always Jeff! I'll add the binaries to the release page.
