### ISSUE TITLE
Questions about UI values

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#48]
Two things:

1) dB per octave attenuation in version 0.13.2 is out of order, it current lists -0, -3.0, -1.5, -6. I assume it's meant to go -0, -1.5, -3, -6?

For the second one I don't know if it's maybe a convention that I'm misunderstanding but:

2) ADSR values seem reversed. A cursory playing around makes it seem like "15" is 0 (off) and "0" is infinite. Please correct me if I'm wrong. It seems backwards to me from the way ADSR is usually implemented.

I'm also still serious about exploring alternative UI layouts to support 4-OP mode and have a few sketches, but I'll share this in another issue in a few weeks.

**Comment by bsutherland** [comment]
Hi.

1) Yes you're right - from memory it's a quirk of the way that the registers themselves are set in the OPL, combined with laziness on my part :) If you take look at the DOSBox OPL emulator source code you'll see why.

2) This is also related to the OPL itself. You're right that the ADSR values are a little unusual compared to the way they work on most devices. The values are actually the values which are programmed directly in to the OPL registers. Think of A, D and R as rates, not durations - higher is faster. For people familiar with software that works with a real OPL device, these values are familiar (eg AdlibTracker). This plugin is mainly aimed at those people, so I stuck with that.

Hope that helps!
