### ISSUE TITLE
Location and method of loading presets is not obvious

### ISSUE THREAD

**Issue by dannynyman** [bsutherland/JuceOPLVSTi#50]
Where can i find presets for this plugin?

**Comment by bsutherland** [comment]
They're included in the Instruments directory in the Windows release. The .sbi files. You can drag and drop them into the UI, or use the Load SBI Instrument button.

I really should do something to make this more obvious..

**Comment by bsutherland** [comment]
(not fixed, but combining with this related issue: https://github.com/bsutherland/JuceOPLVSTi/issues/38)
