### ISSUE TITLE
Velocity sensitivity delay in triggering

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#51]
I've been playing around with the synth live and I've found there's a weird behavior where sometimes the velocity of the note doesn't match what I was playing, or it "shows up" a few notes later. If I try to strike a lot of loud notes with sensitivity on heavy, sometimes an occasional hard strike will 'sound' (ring out) softly. When that is the case, usually the loud note will "appear" up to three or four notes later, even if I'm pressing the keys softly after the soft-sounding hard strike.

It's easiest to reproduce the bug on the same pitch, but it does happen fairly often. I've read a few other bugs so this does seem to be a pretty common occurrence.

I'm not sure I'm describing the behavior very clearly, but it might be something that requires audio/video if you can't reproduce it yourself on the PC version.

I'm using Logic Pro X 10.2.3 and the 0.13.2 version on the Mac.

**Comment by bsutherland** [comment]
Yes, I'm afraid this is a long standing bug which I haven't looked at for a while. I couldn't find the cause last time I looked at it, but it's probably the most serious remaining bug I know of, so it'll probably be the next issue I try to address.

**Comment by bsutherland** [comment]
Not fixed yet, but combining into a single ticket:
https://github.com/bsutherland/JuceOPLVSTi/issues/26
