### ISSUE TITLE
Loading an SBI that's already Loaded Crashes the Plugin (and DAW)

### ISSUE THREAD

**Issue by TheGitMagician** [bsutherland/JuceOPLVSTi#55]
To reproduce:
-import an SBI file
-import the same SBI file again

==> crash

**Comment by bsutherland** [comment]
Thanks for the report! I couldn't reproduce this on my machine, so could you please tell me:

- OS
- DAW
- plugin version
- which SBI file imported
- drag and drop or using "Load .SBI instrument" button?

Thanks!

**Comment by TheGitMagician** [comment]
I'm very sorry - I swear the problem was reproducable yesterday (Win 10 x64, Sonar Producer v23, plugin v0.13.4, using the "Load .SBI instrument" button with any of the supplied SBI-files).

However, today whatever I try I can't reproduce the problem ... so, sorry for wasting your time. I'll do some further investigation but as of right now this issue can be closed.

**Comment by bsutherland** [comment]
No problem at all! Please let me know if you run into it again. I'll close this for now.
