### ISSUE TITLE
Operator feedback doesn't work properly

### ISSUE THREAD

**Issue by fn0rd23** [bsutherland/JuceOPLVSTi#57]
OS: Win8.1
Reaper 4.77
Juceoplvsti 0.14.1

If you set operator feedback it seems that the actual feedback value is the slider value divided by 2 giving you effectively only feedback values of 0,1,2,3. Odd numbered feedback values give the same sound as the next lower even numbered value. A feedback value of 6-7 at full modulation shoud generate noise which it doesn't with Juceoplvst.

**Comment by bsutherland** [comment]
Thanks for the report - I'll look into it!

**Comment by bsutherland** [comment]
You were absolutely right! I was missing a bit-shift. I've fixed this, and will include the fix in the next release.

Thanks a lot for your great QA work!

**Comment by bsutherland** [comment]
Should be fixed in 0.14.2
