### ISSUE TITLE
Visual bug - DDL turns into black box (0.14.2)

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#58]
0.14.2
Logic Pro X 10.2.4
Mac OSX 10.12

A minor bug but the DDLs still turn into empty boxes when selected (i.e. the green outline disappears until the object loses focus). 

It's a minor holdover from 0.14.1 and much less jarring than the white boxes around toggles. Great work so far! This version has made it a lot easier to use overall.

**Comment by bsutherland** [comment]
Thanks! Yeah, as per your previous suggestion I'd like to replace the dropdowns completely which should solve this problem ;)

**Comment by fn0rd23** [comment]
I have the same issue on Windows with Reaper. Also the Frequency value changes under some conditions.
If you set Frequency to 12 and close and reopen the Vst window, the value changes to 15. If the value is at 15 and you reopen the window, the box is empty, the effective value is still 15. Other values seem to work normal and stay at its value.

**Comment by bsutherland** [comment]
@fn0rd23 That is an issue, but I think it's a different one,  so I'm going to split it into another ticket. Thanks.

**Comment by bsutherland** [comment]
@gdreyband Long time no see :)

I finally fixed the colours on the dropdowns in the latest release:
https://github.com/bsutherland/JuceOPLVSTi/releases/tag/1.0.0
