### ISSUE TITLE
Planned UI improvements

### ISSUE THREAD

**Issue by bsutherland** [bsutherland/JuceOPLVSTi#59]
> I'll be revisiting the UI again in the future, and like last time I'll make sure to do the reorganizations myself to spare you the effort. Key areas to address at some later date:
> 
> Moving the location of feedback entirely.
> Typography, color, "pixel perfect" UI

@gdreyband Hope you don't mind if I keep track of this here.

About typography and color, please let me know what you had in mind!

- Color: Personally I'd like to stick with the "monochrome" theme (because it keeps things simple for me as a non-UI guy, and I think it suits the theme), but I'm open to suggestions
- Pixel perfect: I guess you mean reworking the "high-res" bits to look more "low-res" like the waveform icons? If so, I'm definitely on board with that!
- Typography: Yes, from the beginning I wanted to use the font from the DOS game Syndicate, but I couldn't find an existing font conversion of it and there were bigger priorities at the time
(Syndicate font as bitmap here: http://syndicate.lubiki.pl/synd/rework/synd_rework_data_fonts.php)

![image](https://cloud.githubusercontent.com/assets/169313/23819851/b9fef54a-064f-11e7-81c4-f4b6ead0c1c5.png)

Looking forward to seeing what you have in mind!

**Comment by gdreyband** [comment]
Not a problem, I was going to run any changes by you. To clear up what I meant more generally:

Color: I don't mind monochrome or simple colors, but I think the green was only picked out of convenience since it's one of the first defaults in Juce. Not a criticism, but we can definitely find something that looks a bit more "vintage" without starting from scratch.

Pixel perfect: What I mean is that objects are snapped to the Juce grids and a few of the alignments were done by hand, so there might be a few alignment issues. In general I also want the UI to be prettier. It's a surprisingly easy to use and understand FM synth, and I want to make it look a bit friendlier too. There's a ton of really inscrutable FM synths that are functional but really confusing. [VOPM](http://www.vst4free.com/free_vst.php?plugin=VOPM&id=1066) is a perfect example of that.

Typography: Perhaps it's my own nostalgia talking, but I was thinking more [DOS font](https://damieng.com/blog/2011/03/27/typography-in-16-bits-system-fonts) (IBM PC VGA) but I admit it's not actually a great font. It certainly says "80s and 90s PC font" than the current default.

**Comment by Badope6** [comment]
Sorry if I weren't supposed to comment on this but;

I am in love with the simplicity of the looks of the software and that is, for me atleast, a strong and important thing when having something with FM sound designing.

To me the font is perfectly fine and keeps it nice and general, but if you insist to use a more classic one, I would like it if it were possible to have an option or separate files that let's you have the current font and/or switch to another one. But this is just nitpicking I suppose.

Also terribly sorry for asking this (I know this is totally offtopic), but would it be possible to try 4op/OPL3 one time in the future? :D

Again sorry if I weren't supposed to be commenting on this.

**Comment by bsutherland** [comment]
Please comment away! :) I appreciate feedback and at the moment github issues, YouTube comments and the Facebook page are the only communication channels.

Have been meaning to reply on this issue but gave been busy.

First, I agree with both of you that part of the OPL's appeal is it's simplicity and functionality as an FM synth.

About fonts: I'd prefer to steer away from a DOS "textmode" look. For that, there's AdLib tracker :) So if we go for a new font I'd like to aim for a font that's more "classic DOS game", with a sci-fi theme. That said, although the current font is a bit bland, it is definitely functional. I don't want to change font if it hurts readability (keeping in mind that there are Korean and Japanese users too).

About colour, again I went with green for the Syndicate look. As a programmer from the 256 colour era, I opted for #0F0, #080 etc :) @gdreyband, I guess you're thinking of a different shade of green, and I'm not against that if it brings it closer to a Syndicate look and feel.

@badope6 thanks for your comments, I do need to keep in mind that many existing users may not prefer significant UI changes. I might open up a poll on this somewhere. By the way, how do you like the UI changes so far in recent versions? Feedback knob, component layout etc? The major remaining change I'd like to make is changing frequency selectors (as suggested by gdreyband) to another component that doesn't require multi clicks, such as a slider or knob.

About OPL3 4-op mode.. It's a frequent request :) but unfortunately one that I probably won't fulfil for a number of reasons I've mentioned in other tickets.

**Comment by gdreyband** [comment]
Ah, I was about to respond to a few of those things. The short version is that I wouldn't propose anything that's a super drastic change, especially if it affected things like readability, usability, etc. I think there's something to be said for a no-nonsense synth, but I do think it could use a bit of sprucing up. My first pass at all of this was more to address the larger usability issues (which I'm still not totally happy with), but the second will be more visuals. 

I'm not a visual designer, but I'd like to lean into this project for fun. I'll be taking my time with this and making sure I don't do anything to make it worse :)

**Comment by Badope6** [comment]
My personal experience with JuceOPL is that GUI has gotten better and having a better workflow that previous builds.

With that said, I think having a dropdown menu for freq selectors keeps it modern and perhaps stimulates the workflow (e.g. with a slider trying to find the right freqmultiplier can cost longer than directly selecting it from a dropdown menu, atleast in my experiences).
Again not trying to get in the way of a request by someone else, but just sharing my experience.


About what I meant by 4op;
JuceOPL should stay what it is: an OPL2 emulator VST and it's perfect for what it needs to be.
I was more talking about a future project that emulates a 4op chip (OPL3 isn't 100% true 4op). Things like VOPM (OPM) work but they aren't really great in particular and I have a feeling that you can build a good working interface and way of operating of such chips. Not trying to force anything, but just an idea for something in the future as a seperate project when you think you're done with JuceOPL and still want to do something like this.

**Comment by bsutherland** [comment]
@gdreyband I took a look at the VSTs you mentioned. I like the look of 38911 - looks clean, big and simple. FM Drive is on a whole different level .. that is an amazing UI. There must be a lot of code and graphic design behind that :) YMVST I'm not so keen on personally. By all means take your time, have fun, and show me what you come up with!

@Badope6 Thanks for your thoughts on the UI. I see your point about losing accuracy with a slider. I'm not much of a usability / UX person, so I've never thought too deeply about UI components, just gone with my instincts.

A quick bit of googling led me to this article:
http://www.lukew.com/ff/entry.asp?1950

I might play around with a few alternatives like the segmented control (a 4x4 grid maybe?), a slider with steppers etc. It's making me rethink quite a few of the existing components, especially the ones with only 2 or 3 options (for example changing the FM / additive switch to buttons as gdreyband has suggested previously).

**Comment by gdreyband** [comment]
I've had this synth on my mind a lot lately, so I took some time this evening to mockup some alternate control mechanisms.

![juceoplvst mockup](https://cloud.githubusercontent.com/assets/9372336/26344181/93840f80-3f53-11e7-9739-d74cde479100.png)

**Comment by bsutherland** [comment]
Gene,

As always, thanks a lot for the effort and thought you've put into this! I really like this mock up, especially:

- flat frequency multiplier table (looks cool too!)
- selector buttons instead of dropdowns
- the look of the keyscale attenuation part (although I'm not quite sure how the visual diagram part would look as you select different values - would the shape of the line change to represent the attenuation?)

I agree that separate buttons for drums might be a little large, but I saw this display on the OP1 synth the other day that I think is pretty cool. Essentially I was thinking of a pixel-art drum kit, where you can select the drum by clicking on it. Minus the monkey.

https://www.youtube.com/watch?v=WtSJd90ad0A

And as always, please excuse me for being very vague about when I might implement this :( It's a combination of being really busy at my day job, which also tends to suck up my willpower for coding out of hours, as well as other projects I'm working on taking up my time. It will happen one day though :)

Cheers,

Bruce

**Comment by gdreyband** [comment]
Not a problem. These are still explorations for simplifying and creating a bit of novelty like the multiplier table, not any sort of decree. It took me 3-4 weeks to just do this since my own job has been quite busy. 

Hopefully you also got a chance to read through my Percussion Mode breakdown from a while ago.

**Comment by gdreyband** [comment]
Small note, the attenuation slider is just a smidge too short, it looks like it skips over intermediate values regularly because there's not enough screen space to reflect that granularity. I'll have to make sure to adjust that for the next version.

**Comment by bsutherland** [comment]
@gdreyband Thank you for all your efforts and contributions! I see that you discovered the excellent ADLplug project too.

I'm closing all enhancement issues, because I'm sorry to say that I don't plan to enhance JuceOPLVSTi further.
