### ISSUE TITLE
Several percussion mode instruments using wrong operator?

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#61]
I know that most percussion other than bass uses only one operator (6 ops and 5 instruments: 2+1+1+1+1) so I had a question.

This could be a misunderstanding of how percussion mode works but I was playing around with it and this seem to be an issue in "Snare" and "Cymbal". They both use the multiplier from the modulator and everything else from the carrier (waveform, envelope, attenuation).

Tom and hi-hat use everything from the modulator. I think the Snare and Cymbal should also be controlled entirely by the modulator, right?

Bass seems to work "as it should" although I don't really know what is actually going on in these different modes.

Let me know if this isn't clear.

**Comment by bsutherland** [comment]
Hi Gene,

Sorry for the slow reply.

When I was researaching the OPL initially, there was surprisingly little clear documentation on percussion mode, even in the official Yamaha datasheets. The UI is just an interface to the OPL registers, so it should be behaving as a "real" OPL would, assuming the DOSBox emulation is accurate.

When you say that everything should be controlled by the modulator, is that based on some kind of documentation, or maybe some other application like Adlib Tracker? Or you mean from a usability point of view?

**Comment by gdreyband** [comment]
For documentation, the page I tend to read a lot has been this one: http://www.fit.vutbr.cz/~arnost/opl/opl3.html
The doc he refers to is this: http://www.fit.vutbr.cz/~arnost/opl/opl3_doc.zip (covers what's in adlib.doc mentioned below)

specifically this section:

"Percussion Mode

In this mode 6 operators are used to produce five different percussion instruments:

Bass Drum (2 operators)
Snare Drum (1 operator)
Tom-Tom (1 operator)
Cymbal (1 operator)
Hi-Hat (1 operator)
Because these instruments occupy only three melodic channels, only Bass Drum, Snare Drum and Tom-Tom frequencies can be set. Cymbal and Hi-Hat frequencies are fixed.

This mode is identical with that of OPL2. For more details see ADLIB.DOC."

---------------------

Here's my understanding of the OPL2 operator breakdown: There are 18 operators, but only a hardware limited 9 controllable channels. This causes no issue in standard 9 2-OP FM mode, but in percussion mode it looks like it breaks down like this (parens below indicate a controllable channel): 
6 2-OP FM channels
|(1 2) (3 4) (5 6) (7 8) (9 10) (11 12)|
3 percussion channels (5 instruments)

Bass
(13+14)
Snare + [either cymbal or HH]
(15+16)
Tom Tom + [the other of either cymbal or HH]
(17+18)

No matter what, each of the 5 instruments minus bass is only using one operator, because there's only 6 operators left to even use. Because they share an instrument channel, I don't know if this means that frequency multiplier is simply ignored on the "carrier" channel (16 and 18 for Cymbal and HH), but that's what it sounds like.

Since you're creating a VST instrument and percussion and instruments are all done one channel at a time as opposed to the hardware where you have 9 simultaneous channels, it doesn't make sense to alternate between carrier and modulator for percussion controls other than pure "accuracy". In this case having every percussion mode start on the modulator is just easier. 

Going back to my original bug, the issue is that snare and cymbals both have controls that span BOTH operators (in the UI, not in reality), which seems incorrect.

If you had a VST that was essentially doing what Adlib tracker was doing, alternating could make sense. It's wouldn't be totally unheard of either, many drum kit plugins have multi-out support so every percussion element could be submixed separately on different channels. It's way more effort than it's worth but you could theoretically program it to have 3 channels tied together with the 5 instruments but it would be easier to just make cymbal and HH not respond to frequency controls.

**Comment by bsutherland** [comment]
Hi Gene,

Sorry for the very slow reply. Just a quick one to explain where I'm coming from with the accuracy. I have two long-standing goals for the plugin (one of which will hopefully be realised soon..)

1. The ability to output in a format (eg DRO / VGM) which can be played back under emulation or even on real hardware
2. The ability play live to an actual OPL2 chip (eg: https://hackaday.io/project/18995-opl2-audio-board-for-arduino-raspberry-pi)

This is why I don't want the functionality and internals to drift too far away from the real workings of an OPL2 chip.
