### ISSUE TITLE
Pitch bend range?

### ISSUE THREAD

**Issue by lind777** [bsutherland/JuceOPLVSTi#63]
Hi!

Is there a way to set the pitch bend range for the plugin? It seems to default to +-1 semitone, and I can't find a way to change it.

**Comment by bsutherland** [comment]
Hi lind,

There's no option to set this currently, but seems like a good suggestion.
Do you know how other plugins typically handle this?

**Comment by lind777** [comment]
Cool!
This may be super obvious, but I believe pitch bend (and range) are typically handled using 14-bit RPNs. Take a look at https://www.midikits.net/midi_analyser/pitch_bend.htm <https://www.midikits.net/midi_analyser/pitch_bend.htm>
for some hopefully useful hints.

How the RPNs interface with the OPL registers is beyond me. I’m guessing since pitch bend already has a standardized implementation, maybe the range is just a scalar somewhere along the way.

Maybe something can be gleaned from this example plugin?
https://www.codeproject.com/articles/19621/c-synth-toolkit-part-ii <https://www.codeproject.com/articles/19621/c-synth-toolkit-part-ii>

Mind you, I have a decent handle on PureData, and - oddly - LISP, but I’m not a programmer.
L

**Comment by lind777** [comment]
If one looks at the receiving end of things, this section:

`void AdlibBlasterAudioProcessor::applyPitchBend()
{   // apply the currently configured pitch bend to all active notes.
	for (int i = 1; i <= Hiopl::CHANNELS; i++) {
		if (NO_NOTE != active_notes[i]) {
			float f = (float)MidiMessage::getMidiNoteInHertz(active_notes[i]);
			f *= currentScaledBend;
			Opl->SetFrequency(i, f);
		}
	}
}`

...in _PluginProcessor.cpp_ is doing something. Is there a way to add a scaling to the **currentScaledBend** variable?

**Comment by bsutherland** [comment]
Sorry for the very slow reply!

I was wondering about how they handle it from a UI point of view, but I found an example in another plugin. I see that they basically just add another knob which sets the pitch-bend range.

Sorry to say I haven't worked on the plugin for a very long time, and not sure when I will again, but I'll keep this ticket open. Thanks for the suggestion.

**Comment by bsutherland** [comment]
I'm closing this issue, because I'm sorry to say that I don't plan to enhance JuceOPLVSTi further.

I recently found out about an excellent project called ADLplug. It is maintained, and does everything which JuceOPLVSTi does and more. I don't know whether it supports pitch bend, but in case you're interested:

https://github.com/jpcima/ADLplug
