### ISSUE TITLE
Updated GUI (minor changes)

### ISSUE THREAD

**Issue by gdreyband** [bsutherland/JuceOPLVSTi#65]
[PluginGuiGD_12-13-2017.zip](https://github.com/bsutherland/JuceOPLVSTi/files/1557202/PluginGuiGD_12-13-2017.zip)
I couldn't push via source tree for whatever reason, so here's the updated GUI.

The channel usage grid will be off center, as will the version number but I've made a bunch of fixes including:

-Visual alignment
-Resizing group elements, as well as GUI size (minor, 860x520 -> 884x528)
-Adjusting colors (a few box outlines were the wrong color)
-Renaming components in JUCE to reflect consistent naming conventions.

**Comment by bsutherland** [comment]
Great, thanks a lot Gene! I'll take a look on the weekend.

The permissions on the repo only allow the owner to push directly. Contributions on GitLab are usually done via pull-requests, Here are the instructions on forking and creating a pull-request:

https://help.github.com/articles/about-forks/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

That way, the code gets attributed to you, it's easy for me to review changes, and lots of other advantages.

Thanks again.

**Comment by bsutherland** [comment]
Hey Gene, haven't forgotten about this, but worked all weekend. Holidays coming up, maybe some time to work on it then.
