### ISSUE TITLE
How to use Nuked OPL3 Emulator

### ISSUE THREAD

**Issue by litaniast** [bsutherland/JuceOPLVSTi#66]
https://www.vogons.org/viewtopic.php?f=9&t=37782&sid=78834a66ca8a4893c0ec399a0bfb9094

Many people said that's the most accurate emulation of OPL3. It's can also apply for OPL2 sound. I think if JuceOPLVSTi would have the option to choose this, it would be better. (Of course, OPL core selection is option)

**Comment by bsutherland** [comment]
Hi litaniast,

Yes, I remember I tried to integrate Nuked a few years back. It definitely looks very promising but at the time I couldn't get any sound out of it.. I must have been missing something small but important :(

I definitely think this is a good idea. Unfortunately my time and motivation for working on C++ is low at the moment :( I'm always happy to accept pull requests if you know any developers willing to take this on though :)

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, has multiple emulator cores including two versions of Nuked, and does everything which JuceOPLVSTi does and more. In case you're interested:

https://github.com/jpcima/ADLplug
