### ISSUE TITLE
JuceOPLVSTi doesn't work in FL Studio on Mac

### ISSUE THREAD

**Issue by Gothippy** [bsutherland/JuceOPLVSTi#69]
Hello together,

i have a problem. I installed JuceOPLVSTi for OSX on my mac and i work with the programm Fl Studio 20. But it doesn't work. It show's on the channels everywhere an **R**. (See attached on the photo)  I think it have to do with dis. Can somebody help me?

![screenshot](https://user-images.githubusercontent.com/39248282/44621678-8db29d80-a8aa-11e8-8c5b-1a94c2597446.jpg)

**Comment by bsutherland** [comment]
Hi,
I don't have a Mac, and the last OSX build contributed was a very long time ago.
Someone recently contributed some changes for OSX though, so I'll see if they can build a new binary soon.

**Comment by splashdust** [comment]
Hi,

I managed to compile JuceOPLVSTi for OS X as an AU plugin. Weren't able to compile the VST version, as JUCE seems to have dropped built-in support for VST2.

However, the AU version appears to work fine with Ableton Live 10. Perhaps it'll work for FL Studio as well.

[JuceOPLVSTi.component.zip (1.0.0)](https://github.com/bsutherland/JuceOPLVSTi/files/2617381/JuceOPLVSTi.component.zip)

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, has builds for Windows and OSX, and does everything which JuceOPLVSTi does and more. In case you're interested:

https://github.com/jpcima/ADLplug

**Comment by bsutherland** [comment]
I've just created a small new release (1.0.1), and rebuilt as an AU component.
