### ISSUE TITLE
Question about "SBIx\1d" file format

### ISSUE THREAD

**Issue by jpcima** [bsutherland/JuceOPLVSTi#74]
Hello @bsutherland. I want to ask about the SBI format which JuceOPLVSTi saves.

As contributor of [OPL3BankEditor](https://github.com/Wohlstand/OPL3BankEditor) and maker of a OPL synth [plugin](https://github.com/jpcima/ADLplug) myself, I am interested to know how to import this format.

The goal of the editor is to support most OPL instrument formats and import/export between them.
Recently I have tried to load SBI files by JuceOPLVSTi located at this page: http://linuxsynths.com/JuceOPLPatchesDemos/juceopl.html

This format is currently unknown to the bank editor. I know it looks extremely similar to regular SBI, does it exist outside of JuceOPLVSTi or was it created for the purpose of this plugin exclusively?
If so, does it have anything special added to its specification that I should take in consideration?

Thanks

**Comment by jpcima** [comment]
>I don't believe it varies from that format in any way, but if you find any issues, please let me know.

There is a problem, because this is not completely compliant to the format.
The specification as indicated on the wiki page lacks some information.

In the 16 byte payload of SBI, there are supposed to be the following fields:
- byte 11: AdLib drum number
- byte 12: note offset
- byte 13: percussion note number

Problem: JuceOPLVSTi fills 0x20 in the last 5 bytes. As such, if the editor loads this as a regular SBI, it takes it as a drum instrument, and finds it to have a note offset and percussion key, which is all incorrect.

In the bank editor PR that is linked, I put in place a special workaround to handle JuceOPLVSTi's files.
 
About the question I said before: JuceOPLVSTi has the header bytes "SBI\x1d" which is different from original specification of "SBI\x1a".
Have you created this header for JuceOPLVSTi specifically, or is this idea originated from something else?

**Comment by bsutherland** [comment]
Hi,
The SBI format should be as described here, the regular SBI format:
http://www.shikadi.net/moddingwiki/SBI_Format
I don't believe it varies from that format in any way, but if you find any issues, please let me know.
