### ISSUE TITLE
JuceOPLVSTi doesn't work in Reaper on Windows x64

### ISSUE THREAD

**Issue by DonkeyHang** [bsutherland/JuceOPLVSTi#76]
when i open the instruments, Reaper were stopped working...

**Comment by sorang** [comment]
I have the same setup and no problems.

What versions are you running of Reaper and JuceOPL? And are they x64 or
x86?
To my knowledge Reaper doesn't have an error log but check the logs in the
Event Viewer in Windows, maybe they ship some there.

**Comment by KrikIDDQD** [comment]
Try to install Visual C++ Redistributable for Visual Studio 2015. I had a similar problem in Renoise (Failed to initialize) until I installed this.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by bsutherland** [comment]
Thanks @KrikIDDQD !
