### ISSUE TITLE
Timing in Renoise OS X - Note Trigger Timing Drift

### ISSUE THREAD

**Issue by kirkmarkarian** [bsutherland/JuceOPLVSTi#78]
I downloaded the Audio Unit for Renoise, and changed the audio rate to 44.1. Put in a set of 4 quarter notes at C, E, G, and A with a total of 16 sixteenth notes for the singular pattern. Tempo is 135. Just wanted to see if anything has changed at all, but I am still getting drift. Sounds like a 4th grader learning how to play bass-drum for the first time while reading sheet music.  

There's a random drift at the end of the pattern after about 3 - 4 bars of looping.  I added more instruments just to see if my hearing is "off", but it's not.  Goofy little 4th-grader is having trouble keeping time.  Will there be a fix for this?  It would be neat to have an Audio Unit of this amazing synth that is able to keep time properly :D

**Comment by bsutherland** [comment]
Thanks for the report. Unfortunately, this project is basically unmaintained now. Also, I don't have a Mac, so all the OSX versions were always kindly built by volunteers.

Not sure what version you're working with, but there hasn't been an OSX build for a while. My best suggestion would be to try building the latest version yourself and see if that works. If it does, please send me your build so others can benefit from your work too ;)

**Comment by kirkmarkarian** [comment]
Bummer.  Wish I was a programmer, 'cuz I probably would make it work.  Oh well.  Thank you spending the time to make the plugin in the first place.  It brings back good memories!  :D

**Comment by bsutherland** [comment]
I recently found out about an excellent project called ADLplug. It is maintained, has builds for Windows and OSX, and does everything which JuceOPLVSTi does and more. In case you're interested:

https://github.com/jpcima/ADLplug

**Comment by bsutherland** [comment]
(closing in favour of #64 )
