### ISSUE TITLE
Link for OsX is broken

### ISSUE THREAD

**Issue by Nazacheres** [bsutherland/JuceOPLVSTi#80]
https://drive.google.com/open?id=0B3RK-KfkucDQfm5EVnF1UWtxQmRtWlg5dXY3b3hvaUtkb1JKekNTdWFLVUphaU1Fb3J0bjA&authuser=0

**Comment by bsutherland** [comment]
Sorry, I get a 404 on the link.
If you're looking for a great OPL emulator VST which works on OSX, I'd recommend ADLPlug:
https://github.com/jpcima/ADLplug
