### ISSUE TITLE
Compile error - PluginGui.h

### ISSUE THREAD

**Issue by tank-trax** [bsutherland/JuceOPLVSTi#82]
ran into a little snag
building on Debian Buster using JUCE v5.4.5

```
make CONFIG=Release
Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling ChannelButtonLookAndFeel.cpp
In file included from ../../Source/ChannelButtonLookAndFeel.cpp:12:
../../Source/PluginGui.h:131:39: error: ‘nonexistent’ is not a member of ‘juce::File’
  File instrumentLoadDirectory = File::nonexistent;
                                       ^~~~~~~~~~~
../../Source/PluginGui.h:132:39: error: ‘nonexistent’ is not a member of ‘juce::File’
  File instrumentSaveDirectory = File::nonexistent;
                                       ^~~~~~~~~~~
make: *** [Makefile:147: build/intermediate/Debug/ChannelButtonLookAndFeel_6dd4cd32.o] Error 1
```

found this in `JUCE/modules/juce_core/files/juce_File.h`

    /* These static objects are deprecated because it's too easy to accidentally use them indirectly
       during a static constructor, which leads to very obscure order-of-initialisation bugs.
       Use File::getSeparatorChar() and File::getSeparatorString(), and instead of File::nonexistent,
       just use File() or {}.
    */

made the following modifications to lines 131 and 132 of PluginGui.h

change 

```
	File instrumentLoadDirectory = File::nonexistent;
	File instrumentSaveDirectory = File::nonexistent;
```
to 
```
	File instrumentLoadDirectory = File();
	File instrumentSaveDirectory = File();
```

compiled successfully 

```
Linking JuceOPLVSTi - Shared Code
Linking JuceOPLVSTi - VST
```

**Comment by bsutherland** [comment]
Thank you for the report! I guess this is due to a change in Juce .. I haven't compiled the plugin in a long time :) JuceOPLVSTi is essentially unmaintained I'm afraid, but I'm sure this report will help others trying to compile. Thank you!

**Comment by bsutherland** [comment]
changed in 6bdb3e452486c2666528f6551b18d8613d246df9
