### ISSUE TITLE
contribute_sbi_presets_here

### ISSUE THREAD

**Issue by itsmhwk** [bsutherland/JuceOPLVSTi#84]
[doom-box.zip](https://github.com/bsutherland/JuceOPLVSTi/files/4538013/doom-box.zip)

**Comment by bsutherland** [comment]
Thank you! I'll look through these and add when I have some time.

**Comment by itsmhwk** [comment]
Hey, 
Thanks that'd be great! What does it being closed mean though? 
Kind Regards, Trey

Sent from Yahoo Mail on Android 
 
  On Sat, 16 May 2020 at 9:36 am, Bruce Sutherland<notifications@github.com> wrote:   


Closed #84.

**Comment by bsutherland** [comment]
The zip file doesn't seem to have any .sbi files? It's a copy of Doom right?

**Comment by itsmhwk** [comment]
I believe so yeah, I followed the instructions as best I could hahaha

Sent from Yahoo Mail on Android 
 
  On Sun, 17 May 2020 at 9:52 am, Bruce Sutherland<notifications@github.com> wrote:   


The zip file doesn't seem to have any .sbi files? It's a copy of Doom right?
