### ISSUE TITLE
License for JUCE-dependent code needs to be GPLv2-or-later

### ISSUE THREAD

**Issue by d235j** [bsutherland/JuceOPLVSTi#86]
https://github.com/bsutherland/JuceOPLVSTi/blob/master/COPYING is the verbatim GPLv2 text.

JUCE is distributed under two licenses: proprietary and GPLv3. GPLv2 and GPLv3 are incompatible without an "or later" specifier. While the JUCE-dependent components can be argued to be a derivative work of JUCE, it would be ideal if this could be clarified.

My recommendation is to add a statement at the top of the COPYING file, indicating that the software is available under GPLv2 or later. A statement in the main repo README would do as well.

All the DOSBox source files already are GPLv2 or later, or LGPLv2.1 or later (which is compatible).

**Comment by bsutherland** [comment]
Thanks for the information, I wasn't aware of this. I'll look into it when I have time to spare.

**Comment by d235j** [comment]
I believe JUCE used to be available under GPLv2 as well, and/or much of its source still has a header indicating it's under v2 *or* v3. However, adding *or later* is probably the most flexible solution here.

Thanks!

**Comment by bsutherland** [comment]
https://github.com/bsutherland/JuceOPLVSTi/commit/7125cf0256111e1aa2e0ce6d3e109a6545509331
