### ISSUE TITLE
Setting don't fit in dialog

### ISSUE THREAD

**Issue by muranyia** [bsutherland/JuceOPLVSTi#87]
On my Linux system the dialog window holding settings is too small, therefore the controls are partly hidden:
![Screenshot from 2020-05-17 16-45-56](https://user-images.githubusercontent.com/7562080/82151962-a02ef080-985e-11ea-8ce5-925ecf08562e.png)

Was the dialog be sizable or having a vertical scroll bar, the problem would be gone.

**Comment by bsutherland** [comment]
Hi muranyia,

Sorry to say that I never built or ran the plugin on Linux, and it's essentially unmaintained :( That said, are you sure that dialog is part of the plugin and not part of the VST host? I don't recognize it.

**Comment by muranyia** [comment]
It's part of the standalone app. It might come from a template, as I've seen the same dialog with other standalone/VST apps. But with the other apps, a scrollbar is present.

**Comment by bsutherland** [comment]
I didn't know there was a standalone app :) Where did you download it from?

**Comment by muranyia** [comment]
Uh... I came from [discodsp.com](https://www.discodsp.com/opl/) and pulled it from [reales/OPL](https://github.com/reales/OPL) and I guess I ended up here because they don't maintain an issue tracker. Looking back, the idea does not seem the best... I got lost, my bad!
